[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@evvm/testnet-contracts/=src/',
    '@solady/=lib/solady/src/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    # Cross-chain remappings
    ## Hyperlane
    '@hyperlane-xyz/core/=lib/hyperlane-monorepo/solidity/',
    ### LayerZero
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/contracts=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/contracts',
    '@layerzerolabs/lz-evm-messagelib-v2/contracts=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/contracts',
    ## Axelar
    '@axelar-network/axelar-gmp-sdk-solidity/contracts=lib/axelar-gmp-sdk-solidity/contracts',
    ## Risc0
    '@risc0/contracts/=lib/risc0-ethereum/contracts/src'
]
solc = "0.8.30"
optimizer-runs = 300
via_ir = true
ffi = true
fs_permissions = [
    { access = "read", path = "./input" },
    { access = "read", path = "./target" },
    { access = "read", path = "./script" },
    { access = "read-write", path = "./script/helpers" },
    { access = "read-write", path = "./deployments" }
]

# Fork configuration for Base Sepolia
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
